### ISSUE TITLE
Upstreaming OCaml packages to nixpkgs

### ISSUE THREAD

**Issue by superherointj** [anmonteiro/nix-overlays#82]
I wasn't aware of your overlay repository before I started packaging / upstreaming packages to nixpkgs.
I understand it is not your priority to upstream your packages.

Packages already upstreamed to nixpkgs (some in a newer version):
* [arp](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/ocaml-modules/arp/default.nix) (2.3.2)
* [bigstring](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/ocaml-modules/bitstring/default.nix) (4.1.0)
* camlbz2 -> [bz2](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/ocaml-modules/bz2/default.nix) (0.7.0)
* [cudf](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/ocaml-modules/cudf/default.nix) (0.9)
* [dose3](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/ocaml-modules/dose3/default.nix) (6.1)
* [easy-format](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/ocaml-modules/easy-format/default.nix) (1.2.0)
* [junit](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/ocaml-modules/junit/default.nix), [junit_alcotest](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/ocaml-modules/junit/alcotest.nix) (2.0.2)
* [magic-mime](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/ocaml-modules/magic-mime/default.nix) (1.1.3)
* [menhir](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/ocaml-modules/menhir/default.nix) (20210419 *newer*)
* [ocamlgraph](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/ocaml-modules/ocamlgraph/default.nix) (2.0.0)
* [ocplib-endian](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/ocaml-modules/ocplib-endian/default.nix) (1.1)
* [parmap](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/ocaml-modules/parmap/default.nix) (1.2.3)
* [ppx_gen_rec](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/ocaml-modules/ppx_gen_rec/default.nix) (2.0.0)
* [ppx_import](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/ocaml-modules/ppx_import/default.nix) (1.8.0)
* [sedlex](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/ocaml-modules/sedlex/2.nix) (2.3)
* [zmq](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/ocaml-modules/zmq/default.nix) (20180726) *Already has `dune-configurator`.

[I haven't included all yet.]

Consider testing them from upstream and removing it from your overlay in case it works for you.

My goal here is to avoid duplication, avoid drift and find edge cases to be fixed on upstream.

I'll keep updating this issue as I go through the process of upstreaming to Nixpkgs  (packages that overlaps yours).

**Comment by ulrikstrid** [comment]
More packages

- https://github.com/NixOS/nixpkgs/pull/128598
- https://github.com/NixOS/nixpkgs/pull/128600

**Comment by anmonteiro** [comment]
#90 addresses the reported packages in full. The only difference for now is that sedlex_3 needs to be upstreamed. If there are any volunteers, please go ahead and do it, then report back here.

For newer, upstreamed packages, feel free to open a new issue.
